### PR TITLE
feat: use koanf instead of viper

### PR DESCRIPTION
**Pull request by sysulq**

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm unsure about the PR idea.

I mean this PR seems to get out the blue.

What are you trying to solve ?

Why using koanf instead of viper on this project ?

what could it bring ?

Thanks

Please note I'm not suspicious or sarcastic, I'm simply clueless

I'm a random Gopher, following the project

**Comment by sysulq** [comment]
@ccoVeille Thanks for you attention, I prefer to koanf with less dependencies and more stable interface for multiple/dynamic/remote config support.

And in the near future, kod just need rely on koanf's interface for configs, after supporting WithConfigProvider(p koanf.Provider :-)

**Comment by sysulq** [comment]
FYI: https://github.com/knadh/koanf/wiki/Comparison-with-spf13-viper

**Comment by ccoVeille** [comment]
Thanks

**Comment by ccoVeille** [comment]
Did you try using @zxilly (hi 👋) tool on your code to see the difference of size?

https://github.com/Zxilly/go-size-analyzer

**Pull request merged**
